---
#Database connection setting
dbName: pizza_db #Database Name
dbHost: localhost #MySQL Host
dbUser: root  #MySQL User
dbPassword: ~ #MySQL Password
  
#OneSignal API configuration
#You must create account on OneSignal (https://onesignal.com/) to use notifications and next insert here your keys
#Instrucion: https://documentation.onesignal.com/docs/web-push-typical-setup
oneSignalAppID: ~ #OneSignal API public key
oneSignalRestAPIKey: ~ #OneSignal Private key

#SMTP configuration
#If you want working email's you need configure your SMTP server or use existing SMTP server (ex. Gmail)
smtpHost: localhost #SMTP Host
smtpPort: 567 #SMTP Port
smtpSecure: tls #SMTP Encrypt protocol
smtpUser: user #SMTP User
smtpPassword: password #SMTP Password for user 
smtpAuthorName: Pan Pomocnik #Names in email send to user

#Google reCAPTCHA
#For Google reCAPTCHA Support you need register in reCaptcha service (https://www.google.com/recaptcha/) and paste here below your keys
#Google default keys allow you to run reCaptcha on localhost without register but VALIDATION ALWAYS RETURN TRUE
googleRESiteKey: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
googleRESecretKey: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

#Google Maps (Geocode)
#If you want working with Google Maps you must paste here key from Google API with Geolocalization
googleMapAPIKey: ~

#Format Email
#Here you can edit email content which user get when send email by form on home page
#firstEmailRegisterContent:
# Content when user first time use contact form
# %s - First Name
# %s - Last Name
# %s - Site URL
# %s - Special key

#nextEmailContent
# Content when user have account and use contact form
# %s - First Name
# %s - Last Name
firstEmailRegisterContent: "Dziękujemy za kontakt %s %s. Postaramy się jak najszybciej odpowiedzieć, rozmowy prowadzone z nami jak i odpowiedzi wysyłaj proszę z <a href='%s/user.php?key=%s'>tego</a> miejsca. <b>Link ten służy automatycznie do zalogowania się i umożliwia przeglądanie wszystkich twoich rozmów z nami,  nie podawaj go NIKOMU oraz ZAPISZ GO</b>"
nextEmailContent: "Dziękujemy za kontakt %s %s. Postaramy się jak najszybciej odpowiedzieć, rozmowy prowadzone z nami jak i odpowiedzi wysyłaj proszę ze specjalnego linka który otrzymałeś za pierwszym razem."


#Special salt for passwords
accSalt: ChangeItPlease! #Change it necessarily!
---